// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3JfhZY0dkfXXQwPp5bFo0tTj2vchLQUg',
    appId: '1:303053652609:android:694e746df9ed9ff8d30380',
    messagingSenderId: '303053652609',
    projectId: 'give-structure',
    databaseURL: 'https://give-structure.firebaseio.com',
    storageBucket: 'give-structure.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8pPyPse8pI7qcxGaKWLQd2cMUhku07sg',
    appId: '1:303053652609:ios:b049866ca42dbcdfd30380',
    messagingSenderId: '303053652609',
    projectId: 'give-structure',
    databaseURL: 'https://give-structure.firebaseio.com',
    storageBucket: 'give-structure.appspot.com',
    androidClientId: '303053652609-4dkhhbt03lrm8doqeid40u4q88n42e2j.apps.googleusercontent.com',
    iosClientId: '303053652609-f8drqocio9g7mqsr728955q87gfca0se.apps.googleusercontent.com',
    iosBundleId: 'com.example.give',
  );
}
